api_platform:
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  formats:
    jsonhal: [ 'application/hal+json' ]
    json: [ 'application/json' ]
    html: [ 'text/html' ]